"""Generate the Speakeasy KiCad project from board_def.py.

Run with:  uv run python circuit-synth/generate.py
"""

import os
import pathlib
import re
import shutil
import subprocess
import sys


def main():
    # Verify we're running the local circuit-synth fork, not a stale installed copy.
    import circuit_synth as _cs

    _cs_path = pathlib.Path(_cs.__file__).resolve()
    _fork = (
        pathlib.Path(__file__).resolve().parent.parent.parent
        / "circuit-synth-local"
        / "src"
        / "circuit_synth"
    ).resolve()
    if not str(_cs_path).startswith(str(_fork)):
        print(
            f"ERROR: circuit_synth loaded from wrong location:\n  {_cs_path}\n"
            f"Expected: {_fork}\n\n"
            f"Fix with:\n  uv pip install setuptools && "
            f"uv pip install --editable ../circuit-synth-local --no-build-isolation",
            file=sys.stderr,
        )
        sys.exit(1)

    # Ensure both the standard KiCad symbols and ~/KiCad (EasyEDA library) are on
    # the search path. Setting KICAD_SYMBOL_DIR disables circuit-synth's built-in
    # fallback to /Applications/KiCad, so we must include it explicitly.
    _kicad_system = "/Applications/KiCad/KiCad.app/Contents/SharedSupport/symbols"
    _kicad_user = str(pathlib.Path.home() / "KiCad")
    _kicad_project = str(
        pathlib.Path(__file__).resolve().parent.parent / "speakeasy_lowcost" / "lib"
    )
    _existing = os.environ.get("KICAD_SYMBOL_DIR", "")
    _paths = [p for p in [_kicad_user, _kicad_system, _kicad_project, _existing] if p]
    os.environ["KICAD_SYMBOL_DIR"] = ":".join(_paths)

    from board_def import speakeasy_board
    from board_helpers import (
        add_lcsc_numbers,
        preserve_component_uuids,
        write_jlcpcb_bom,
    )

    # circuit-synth crashes on incremental update (SheetManager bug) so we must
    # generate fresh.  To avoid forcing a KiCad restart, we generate into a
    # temporary folder and then overwrite the real output folder file-by-file.
    # KiCad detects the in-place modification and shows a one-click "Reload"
    # prompt instead of losing track of the open project.
    STAGING = "speakeasy_staging"
    OUTPUT = "speakeasy_lowcost"

    shutil.rmtree(STAGING, ignore_errors=True)

    circuit_obj = speakeasy_board()

    circuit_obj.generate_kicad_project(
        project_name=STAGING,
        placement_algorithm="hierarchical",
        generate_pcb=True,
        preserve_user_components=False,
    )

    # Stabilise the circuit-synth internal tstamp in Speakeasy.json
    _json_path = f"{STAGING}/Speakeasy.json"
    try:
        _jtext = open(_json_path).read()
        _jtext = re.sub(
            r'"tstamps":\s*"[^"]*"', '"tstamps": "/speakeasy/"', _jtext, count=1
        )
        open(_json_path, "w").write(_jtext)
    except Exception:
        pass

    # fix_power_symbol_overlaps(f"{STAGING}/Speakeasy.kicad_sch")
    add_lcsc_numbers(f"{STAGING}/Speakeasy Lowcost.kicad_sch")
    preserve_component_uuids(
        f"{OUTPUT}/Speakeasy Lowcost.kicad_sch",
        f"{STAGING}/Speakeasy Lowcost.kicad_sch",
        net_path=f"{STAGING}/Speakeasy Lowcost.net",
        pro_path=f"{STAGING}/Speakeasy Lowcost.kicad_pro",
    )

    # Copy staging → output, preserving any KiCad-managed files (e.g. .kicad_pcb
    # with user-placed components) that are not regenerated by circuit-synth.
    pathlib.Path(OUTPUT).mkdir(exist_ok=True)
    for src in pathlib.Path(STAGING).iterdir():
        shutil.copy2(src, pathlib.Path(OUTPUT) / src.name)
    shutil.rmtree(STAGING)

    print("KiCad project: speakeasy/speakeasy Lowcost.kicad_pro")

    bom = circuit_obj.generate_bom(project_name=STAGING)
    if bom["success"]:
        print(
            f"BOM: {OUTPUT}/{pathlib.Path(bom['file']).name}  ({bom['component_count']} components)"
        )
    else:
        print(f"BOM failed: {bom.get('error')}")

    pathlib.Path(f"{OUTPUT}/jlcpcb").mkdir(exist_ok=True)
    write_jlcpcb_bom(
        f"{OUTPUT}/Speakeasy Lowcost.kicad_sch",
        f"{OUTPUT}/jlcpcb/speakeasy_lowcost_jlcpcb_bom.csv",
    )

    pdf = circuit_obj.generate_pdf_schematic(project_name=STAGING)
    if pdf["success"]:
        print(f"PDF: {OUTPUT}/{pathlib.Path(pdf['file']).name}")
    else:
        print(f"PDF failed: {pdf.get('error')}")

    gerbers = circuit_obj.generate_gerbers(project_name=STAGING)
    if gerbers["success"]:
        print(
            f"Gerbers: {gerbers['output_dir']}  ({len(gerbers['gerber_files'])} files)"
        )
    else:
        print(f"Gerbers failed: {gerbers.get('error')}")

    _here = pathlib.Path(__file__).parent

    print("\nPanelizing...")
    result = subprocess.run([sys.executable, str(_here / "panelize.py")])
    if result.returncode != 0:
        print("Panelize failed.")

    print("\nGenerating JLCPCB outputs...")
    result = subprocess.run([sys.executable, str(_here / "fab_jlcpcb.py")])
    if result.returncode != 0:
        print("fab_jlcpcb failed.")


if __name__ == "__main__":
    main()
