## Speakeasy Snapcast mDNS Bluetooth WiFi 9dBm Ramp - Edit the settings below.
substitutions:
  name: sc-mdns-bt-w9r
  friendly_name: Speakeasy Snapcast mDNS Bluetooth WiFi 9dBm Ramp

packages:
  - !include common/base.yaml
  - !include common/improv.yaml
  - !include common/snapcast-audio.yaml
  - !include common/wifi-9ramp.yaml

dashboard_import:
  package_import_url: github://W-Floyd/speakeasy/speakeasy-sc-mdns-bt-w9r.yaml@main
  import_full_config: false

esp32:
  variant: esp32s3

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

media_player:
  - id: !extend snapclient_media_player
    hostname: !remove
    port: !remove
