## Speakeasy Snapcast WiFi 8.5dBm Ramp - Edit the settings below.
substitutions:
  name: sc-w85ramp
  friendly_name: Speakeasy Snapcast WiFi 8.5dBm Ramp

  # Snapcast server address and port
  snapcast_server_ip: "192.168.1.1"
  snapcast_server_port: "1704"

packages:
  - !include common/base.yaml
  - !include common/improv.yaml
  - !include common/snapcast-audio.yaml
  - !include common/wifi-85ramp.yaml

dashboard_import:
  package_import_url: github://W-Floyd/speakeasy/speakeasy-sc-w85ramp.yaml@main
  import_full_config: false

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
