## Speakeasy (Snapcast) - Edit the settings below.
substitutions:
  name: speakeasy
  friendly_name: Speakeasy

  # Snapcast server address and port
  snapcast_server_ip: "192.168.1.1"
  snapcast_server_port: "1704"

packages:
  - !include common/base.yaml

dashboard_import:
  package_import_url: github://W-Floyd/speakeasy/speakeasy-snapcast.yaml@main
  import_full_config: false

external_components:
  - source: github://pr#14389
    components: [ snapclient ]
    refresh: 24h

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

media_player:
  - platform: snapclient
    id: snapclient_media_player
    name: ${friendly_name}
    hostname: ${snapcast_server_ip}
    port: ${snapcast_server_port}
    i2s_dout_pin: ${i2s_dout_pin}
