## Speakeasy Snapcast 2ch No Bluetooth - Edit the settings below.
substitutions:
  name: snapcast-2ch-nobt
  friendly_name: Speakeasy Snapcast 2ch No Bluetooth

  # Snapcast server address and port
  snapcast_server_ip: "192.168.1.1"
  snapcast_server_port: "1704"

packages:
  - !include common/base.yaml
  - !include common/snapcast-audio.yaml
  - !include common/second-speaker.yaml

dashboard_import:
  package_import_url: github://W-Floyd/speakeasy/speakeasy-snapcast-2ch-nobt.yaml@main
  import_full_config: false

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
