## Speakeasy Sendspin mDNS No Bluetooth IPv6 - Edit the settings below.
substitutions:
  name: sendspin-mdns-nobt-ipv6
  friendly_name: Speakeasy Sendspin mDNS No Bluetooth IPv6

packages:
  - !include common/base.yaml
  - !include common/sendspin-audio.yaml
  - !include common/ipv6.yaml

dashboard_import:
  package_import_url: github://W-Floyd/speakeasy/speakeasy-sendspin-mdns-nobt-ipv6.yaml@main
  import_full_config: false

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
