substitutions:
  i2s_lrclk_pin: GPIO10
  i2s_bclk_pin: GPIO11
  i2s_dout_pin: GPIO12

esphome:
  min_version: 2026.5.0
  name_add_mac_suffix: true
  project:
    name: w_floyd.speakeasy
    version: "1"

esp32:
  variant: esp32s3
  framework:
    type: esp-idf
    sdkconfig_options:
      # Options: 0=NONE, 1=ERROR, 2=WARN, 3=INFO, 4=DEBUG, 5=VERBOSE
      CONFIG_LOG_DEFAULT_LEVEL: "4"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"
      CONFIG_FREERTOS_PLACE_FUNCTIONS_INTO_FLASH: "n"
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: "y"
      CONFIG_ESPTOOLPY_FLASHFREQ_80M: "y"
      CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM: "16"
      CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM: "64"

logger:
  level: debug

api:

ota:
  - platform: esphome

wifi:
  id: wifi_component
  power_save_mode: none
  post_connect_roaming: false
  ap:
  on_connect:
    - lambda: |-
        char ip_buf[esphome::network::IP_ADDRESS_BUFFER_SIZE];
        id(wifi_component).get_ip_addresses()[0].str_to(ip_buf);
        ESP_LOGW("speakeasy", "IP: %s, RSSI: %d dBm", ip_buf, id(wifi_component).wifi_rssi());

network:
  enable_ipv6: true
  enable_high_performance: true

psram:
  mode: quad
  speed: 80MHz

captive_portal:

improv_serial:

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: ${i2s_lrclk_pin}
    i2s_bclk_pin: ${i2s_bclk_pin}

sensor:
  - platform: internal_temperature
    name: Internal Temperature
