# DAC: MAX98357A (I2S, no I2C). SD_MODE tied to L+R/2 voltage divider for hardware mono mix.
substitutions:
  snapcast_server_ip: "192.168.1.1"
  snapcast_server_port: "1704"

external_components:
  - source: github://W-Floyd/esphome@snapclient2
    components: [snapclient]
    refresh: 0s # Forces ESPHome to check for new branch commits on every compile

media_player:
  - platform: snapclient
    id: snapclient_media_player
    name: ${friendly_name}
    hostname: ${snapcast_server_ip}
    port: ${snapcast_server_port}
    i2s_dout_pin: ${i2s_dout_pin}
    volume_curve_db_range: 40
