[project]
name = "speakeasy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "circuit-synth>=0.12.1",
    "deterministic-zip>=0.1",
    "kikit>=1.8.0",
]

[tool.uv.sources]
circuit-synth = { path = "../circuit-synth-local", editable = true }
