from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

speakeasy_board = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'ESP32-S3-MINI-1U-N4R2', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ESP32-S3-MINI-1U-N4R2'}), 'ref_prefix':'ESP', 'fplist':['EasyEDA:BULETM-SMD_ESPRESSIF_ESP32-S3-MINI-1U-N8'], 'footprint':'EasyEDA:BULETM-SMD_ESPRESSIF_ESP32-S3-MINI-1U-N8', 'keywords':'WiFi Modules', 'description':'', 'datasheet':'https://www.lcsc.com/datasheet/C22356044.pdf', 'pins':[
            Pin(num='65',name='GND',func=pin_types.UNSPEC),
            Pin(num='64',name='GND',func=pin_types.UNSPEC),
            Pin(num='63',name='GND',func=pin_types.UNSPEC),
            Pin(num='62',name='GND',func=pin_types.UNSPEC),
            Pin(num='61',name='GND',func=pin_types.UNSPEC),
            Pin(num='60',name='GND',func=pin_types.UNSPEC),
            Pin(num='59',name='GND',func=pin_types.UNSPEC),
            Pin(num='58',name='GND',func=pin_types.UNSPEC),
            Pin(num='57',name='GND',func=pin_types.UNSPEC),
            Pin(num='56',name='GND',func=pin_types.UNSPEC),
            Pin(num='55',name='GND',func=pin_types.UNSPEC),
            Pin(num='54',name='GND',func=pin_types.UNSPEC),
            Pin(num='53',name='GND',func=pin_types.UNSPEC),
            Pin(num='52',name='GND',func=pin_types.UNSPEC),
            Pin(num='51',name='GND',func=pin_types.UNSPEC),
            Pin(num='50',name='GND',func=pin_types.UNSPEC),
            Pin(num='49',name='GND',func=pin_types.UNSPEC),
            Pin(num='48',name='GND',func=pin_types.UNSPEC),
            Pin(num='47',name='GND',func=pin_types.UNSPEC),
            Pin(num='46',name='GND',func=pin_types.UNSPEC),
            Pin(num='45',name='EN',func=pin_types.UNSPEC),
            Pin(num='44',name='IO46',func=pin_types.UNSPEC),
            Pin(num='43',name='GND',func=pin_types.UNSPEC),
            Pin(num='42',name='GND',func=pin_types.UNSPEC),
            Pin(num='41',name='IO45',func=pin_types.UNSPEC),
            Pin(num='40',name='RXD0',func=pin_types.UNSPEC),
            Pin(num='39',name='TXD0',func=pin_types.UNSPEC),
            Pin(num='38',name='IO42',func=pin_types.UNSPEC),
            Pin(num='37',name='IO41',func=pin_types.UNSPEC),
            Pin(num='36',name='IO40',func=pin_types.UNSPEC),
            Pin(num='35',name='IO39',func=pin_types.UNSPEC),
            Pin(num='34',name='IO38',func=pin_types.UNSPEC),
            Pin(num='33',name='IO37',func=pin_types.UNSPEC),
            Pin(num='32',name='IO36',func=pin_types.UNSPEC),
            Pin(num='31',name='IO35',func=pin_types.UNSPEC),
            Pin(num='30',name='IO48',func=pin_types.UNSPEC),
            Pin(num='29',name='IO34',func=pin_types.UNSPEC),
            Pin(num='28',name='IO33',func=pin_types.UNSPEC),
            Pin(num='27',name='IO47',func=pin_types.UNSPEC),
            Pin(num='26',name='IO26',func=pin_types.UNSPEC),
            Pin(num='25',name='IO21',func=pin_types.UNSPEC),
            Pin(num='24',name='IO20',func=pin_types.UNSPEC),
            Pin(num='23',name='IO19',func=pin_types.UNSPEC),
            Pin(num='22',name='IO18',func=pin_types.UNSPEC),
            Pin(num='21',name='IO17',func=pin_types.UNSPEC),
            Pin(num='20',name='IO16',func=pin_types.UNSPEC),
            Pin(num='19',name='IO15',func=pin_types.UNSPEC),
            Pin(num='18',name='IO14',func=pin_types.UNSPEC),
            Pin(num='17',name='IO13',func=pin_types.UNSPEC),
            Pin(num='16',name='IO12',func=pin_types.UNSPEC),
            Pin(num='15',name='IO11',func=pin_types.UNSPEC),
            Pin(num='14',name='IO10',func=pin_types.UNSPEC),
            Pin(num='13',name='IO9',func=pin_types.UNSPEC),
            Pin(num='12',name='IO8',func=pin_types.UNSPEC),
            Pin(num='11',name='IO7',func=pin_types.UNSPEC),
            Pin(num='10',name='IO6',func=pin_types.UNSPEC),
            Pin(num='9',name='IO5',func=pin_types.UNSPEC),
            Pin(num='8',name='IO4',func=pin_types.UNSPEC),
            Pin(num='7',name='IO3',func=pin_types.UNSPEC),
            Pin(num='6',name='IO2',func=pin_types.UNSPEC),
            Pin(num='5',name='IO1',func=pin_types.UNSPEC),
            Pin(num='4',name='IO0',func=pin_types.UNSPEC),
            Pin(num='3',name='3V3',func=pin_types.UNSPEC),
            Pin(num='2',name='GND',func=pin_types.UNSPEC),
            Pin(num='1',name='GND',func=pin_types.UNSPEC)], 'unit_defs':[] }),
        Part(**{ 'name':'MAX98357AETE+T', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MAX98357AETE+T'}), 'ref_prefix':'U', 'fplist':['EasyEDA:TQFN-16_L3.0-W3.0-P0.50-BL-EP1.5'], 'footprint':'EasyEDA:TQFN-16_L3.0-W3.0-P0.50-BL-EP1.5', 'keywords':'Audio Power OpAmps', 'description':'', 'datasheet':'https://www.lcsc.com/datasheet/C910544.pdf', 'pins':[
            Pin(num='1',name='DIN',func=pin_types.UNSPEC),
            Pin(num='2',name='GAIN_SLOT',func=pin_types.UNSPEC),
            Pin(num='3',name='GND',func=pin_types.UNSPEC),
            Pin(num='4',name='~{SD_MODE}',func=pin_types.UNSPEC),
            Pin(num='5',name='N.C.',func=pin_types.UNSPEC),
            Pin(num='6',name='N.C.',func=pin_types.UNSPEC),
            Pin(num='7',name='VDD',func=pin_types.UNSPEC),
            Pin(num='8',name='VDD',func=pin_types.UNSPEC),
            Pin(num='9',name='OUTP',func=pin_types.UNSPEC),
            Pin(num='10',name='OUTN',func=pin_types.UNSPEC),
            Pin(num='11',name='GND',func=pin_types.UNSPEC),
            Pin(num='12',name='N.C.',func=pin_types.UNSPEC),
            Pin(num='13',name='N.C.',func=pin_types.UNSPEC),
            Pin(num='14',name='LRCLK',func=pin_types.UNSPEC),
            Pin(num='15',name='GND',func=pin_types.UNSPEC),
            Pin(num='16',name='BCLK',func=pin_types.UNSPEC),
            Pin(num='17',name='EP',func=pin_types.UNSPEC)], 'unit_defs':[] }),
        Part(**{ 'name':'AMS1117-3.3', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AMS1117-3.3'}), 'ref_prefix':'U', 'fplist':['EasyEDA:SOT-223-3_L6.5-W3.4-P2.30-LS7.0-BR'], 'footprint':'EasyEDA:SOT-223-3_L6.5-W3.4-P2.30-LS7.0-BR', 'keywords':'Linear Voltage Regulators (LDO)', 'description':'', 'datasheet':'https://lcsc.com/product-detail/Low-Dropout-Regulators-LDO_AMS_AMS1117-3-3_AMS1117-3-3_C6186.html', 'pins':[
            Pin(num='1',name='GND',func=pin_types.UNSPEC),
            Pin(num='2',name='VOUT',func=pin_types.UNSPEC),
            Pin(num='3',name='VIN',func=pin_types.UNSPEC),
            Pin(num='4',name='VOUT',func=pin_types.UNSPEC)], 'unit_defs':[] }),
        Part(**{ 'name':'PH-6Pç«\x8bè´´', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'PH-6Pç«\x8bè´´'}), 'ref_prefix':'CN', 'fplist':['EasyEDA:CONN-SMD_6P-P2.0-L14.0-W5.4'], 'footprint':'EasyEDA:CONN-SMD_6P-P2.0-L14.0-W5.4', 'keywords':'Wire To Board / Wire To Wire Connector', 'description':'', 'datasheet':'https://www.lcsc.com/datasheet/C64659.pdf', 'pins':[
            Pin(num='8',name='8',func=pin_types.UNSPEC),
            Pin(num='7',name='7',func=pin_types.UNSPEC),
            Pin(num='6',name='6',func=pin_types.UNSPEC),
            Pin(num='5',name='5',func=pin_types.UNSPEC),
            Pin(num='4',name='4',func=pin_types.UNSPEC),
            Pin(num='3',name='3',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC),
            Pin(num='1',name='1',func=pin_types.UNSPEC)], 'unit_defs':[] }),
        Part(**{ 'name':'210-A-SMD_02', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'210-A-SMD_02'}), 'ref_prefix':'CN', 'fplist':['EasyEDA:CONN-SMD_210-A-SMD-02'], 'footprint':'EasyEDA:CONN-SMD_210-A-SMD-02', 'keywords':'Screw terminal', 'description':'', 'datasheet':'https://www.lcsc.com/datasheet/C20608465.pdf', 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)], 'unit_defs':[] }),
        Part(**{ 'name':'TestPoint', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TestPoint'}), 'ref_prefix':'TP', 'fplist':[''], 'footprint':'TestPoint:TestPoint_Pad_D1.5mm', 'keywords':'test point tp', 'description':'test point', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':[''], 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':'R res resistor', 'description':'Resistor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_SMD:C_0805_2012Metric', 'keywords':'cap capacitor', 'description':'Unpolarized capacitor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'SW_Push', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SW_Push'}), 'ref_prefix':'SW', 'fplist':[''], 'footprint':'Button_Switch_SMD:SW_SPST_CK_RS282G05A3', 'keywords':'switch normally-open pushbutton push-button', 'description':'Push button switch, generic, two pins', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)], 'unit_defs':[] })])